kumuluzee:
  datasources:
    - jndi-name: jdbc/BooksDS
      connection-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      max-pool-size: 20
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                     <Configuration name="comments">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n [%t] %-5level %logger{36} - %msg%n"/>
                            </Console>
                             <Socket name="socket" host="9e707eb7-9c66-494f-b6ef-8a1ffe388e1e-ls.logit.io" port="23073">
                                  <JsonLayout properties="true"/>
                                </Socket>
                        </Appenders>
                        <Loggers>
                         <Logger name="com.kumuluz.ee.samples.microservices.simple.CommentsResource" level="trace">
                            <AppenderRef ref="Console"/>
                          </Logger>
                            <!-- Default logger -->
                            <Root level="info">
                                <AppenderRef ref="console"/>
                                <AppenderRef ref="socket"/>
                             </Root>
                        </Loggers>
                    </Configuration>'
    loggers:
      - name: ''
        level: INFO
  config:
      start-retry-delay-ms: 500
      max-retry-delay-ms: 900000
      etcd:
        hosts: http://127.0.0.1:2379

